### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [17]:
import numpy as np
import random

vector = []
for v in range(10):

    vector.append(random.uniform(0,1))

print(vector)


[0.26679613126197765, 0.5262956598925345, 0.528102713163286, 0.9699759236505097, 0.9510390037636711, 0.7986530167238383, 0.4094740678742861, 0.7304140469854524, 0.254216500446091, 0.5814779828268156]


In [60]:
vector_np = np.random.rand(10)
vector_np.shape

(10,)

In [63]:
vector_np

array([0.5832518 , 0.11672532, 0.37094719, 0.10552456, 0.15669402,
       0.36992992, 0.53542676, 0.37941071, 0.23394369, 0.95012778])

In [27]:
A = np.array([[11, 14, 17],
             [20, 23, 26],
             [29, 32, 35]])

In [28]:
A.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [48]:
vector_array = np.array(vector) + 10
print(np.round(vector_array,2))

[10.27 10.53 10.53 10.97 10.95 10.8  10.41 10.73 10.25 10.58]


In [47]:
vector_plus_10 = list(map(lambda v: v + 10, vector))
vector_rounded = list(map(lambda v: round(v, 2), vector_plus_10))
vector_rounded

[10.27, 10.53, 10.53, 10.97, 10.95, 10.8, 10.41, 10.73, 10.25, 10.58]

In [50]:
A_2 = np.dot(A, 2)
A_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [49]:
A_3 = A * 2
A_3

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [52]:
vector_square = list(map(lambda x: x**2, vector))
vector_square

[0.07118017565635841,
 0.2769871216217183,
 0.27889247565042397,
 0.9408532924616594,
 0.9044751866797961,
 0.6378466411220874,
 0.16766901226151545,
 0.5335046800336667,
 0.06462602909905739,
 0.33811664451234247]

In [65]:
vector_s = np.square(vector_np)
vector_s

array([0.34018266, 0.0136248 , 0.13760182, 0.01113543, 0.02455302,
       0.13684815, 0.28668181, 0.14395249, 0.05472965, 0.90274279])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [66]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [69]:
result_matrix = np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [70]:
result_matrix_c = np.dot(result_matrix,C)
print(result_matrix_c)

[[0.5202]
 [0.2846]]


In [71]:
result_matrix_d = np.dot(result_matrix, D)
print(result_matrix_d)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [73]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [74]:
vector_np.T

array([0.5832518 , 0.11672532, 0.37094719, 0.10552456, 0.15669402,
       0.36992992, 0.53542676, 0.37941071, 0.23394369, 0.95012778])

In [77]:
column_vector= np.expand_dims(vector_np,axis = 1)
print(column_vector)

[[0.5832518 ]
 [0.11672532]
 [0.37094719]
 [0.10552456]
 [0.15669402]
 [0.36992992]
 [0.53542676]
 [0.37941071]
 [0.23394369]
 [0.95012778]]


In [80]:
column_vector.T
column_vector.T.shape
print(column_vector.T, column_vector.T.shape)

[[0.5832518  0.11672532 0.37094719 0.10552456 0.15669402 0.36992992
  0.53542676 0.37941071 0.23394369 0.95012778]] (1, 10)
